### ISSUE TITLE
reset cache  integration for nextjs 13.4

### ISSUE THREAD

**Issue by khanghoang1702** [apollographql/apollo-client-nextjs#101]
Recently, I have a landing page that get all the app contents in the server side of nextjs with one day revalidate config. and I would like an API in nextjs server that can reset the cache and fetch new data whenever I request and the app also reflect the new data. here my integration in the nextjs app. I wonder do I apply the best practices for the case
`
const client = new NextSSRApolloClient({
  cache: new NextSSRInMemoryCache(),
  link: formatAppContentsResponse.concat(httpLink),
}); 

await client.resetStore();
      await client.query({
        query: ExampleDocument,
        context: {
          fetchOptions: {
            next: { revalidate: 1 },
          },
        },
        fetchPolicy: 'no-cache',
      });`

**Comment by phryneas** [comment]
I'm not exactly sure what you ask here.... where is this code running?

In a server component? In a client component?

**Comment by khanghoang1702** [comment]
Thank your response, I use this in the server component (I mean App API route) to get the new content of the app after I changed

**Comment by phryneas** [comment]
Please make sure that in a request handler like this, you create a new instance of Apollo Client for every single incoming request - otherwise things like query deduplication could mix up queries of multiple users that are incoming at the same time. Calling `resetStore` is not enough to prevent things like that.

You could have 20 requests in the same millisecond, and all of them call `resetStore` at the same time and then start their requests - they would still influence each other. You can't work with a global client here.

That said, if you're not using React SSR, (and this is just a response handler), you also don't need to use the `NextSSRApolloClient`/``NextSSRInMemoryCache`. Just do a `new ApolloClient(...)` inside of that ResponseHandler.

**Comment by phryneas** [comment]
I'm doing some housekeeping so I'm closing some older issues that haven't seen activity in a while. 
If this is still relevant, please feel free to reopen the issue.
