### ISSUE TITLE
is the polls demo really server side?

### ISSUE THREAD

**Issue by yanv1991** [apollographql/apollo-client-nextjs#104]
This is more like a question rather than reporting an issue, but essentially we are noticing in our app that usequery hook is fetching the data in the client side rather than ssr. I was checking this demo https://github.com/apollographql/apollo-client-nextjs/tree/main/examples/polls-demo and I noticed if you disable js in this url https://apollo-next-13-polls.vercel.app/cc the data is not shown.
![Screenshot 2023-09-29 at 5 06 23 PM](https://github.com/apollographql/apollo-client-nextjs/assets/3800032/0803af09-acd5-4998-8558-d17e55fcdd44)

My question is should I fetch this data rather using a RSC?? My dilemma is, we are using paginated data so not sure if I should fetch the initial data in RSC and later concatenate the rest on the fly when user scroll down.

Thanks in advance for the help....

**Comment by phryneas** [comment]
That page is not using RSC, but React's "Streaming SSR" in a client component. That means that on first load, everything on that page will be rendered on the server - but the server doesn't wait for everything to be ready to send it to the browser, but it sends it over chunk-by-chunk. 
And that means that you need JavaScript enabled to "puzzle together" these server-rendered chunks.
If you look at the network tab, you'll still see that no network requests are made for the client (for the first load) - because those were made on the server and rendered on the server.
