### ISSUE TITLE
useSuspenseQuery defaultOptions errorPolicy ignored

### ISSUE THREAD

**Issue by tombryden** [apollographql/apollo-client-nextjs#107]
Hi,

Setting defaultOptions errorPolicy to "all" in NextSSRApolloClient seems to be ignored.

See demo: https://codesandbox.io/p/github/tombryden/experimental-apollo-suspense-bug

Comment out the error policy in useSuspenseQuery hook, you will see runtime error thrown despite the same error policy being declared in default options in `src/apollo/apollo-wrapper.tsx`

**Comment by jerelmiller** [comment]
Hey @tombryden 👋 

`useSuspenseQuery` uses the `watchQuery` default options, which is why the behavior you're seeing seems ignored. Try changing `query` to `watchQuery` and it will work.

```tsx
new NextSSRApolloClient({
  // use the `NextSSRInMemoryCache`, not the normal `InMemoryCache`
  cache: new NextSSRInMemoryCache(),
  defaultOptions: {
    watchQuery: {
      errorPolicy: "all",
    },
  },
  // ...
})
```

I've tested this on a [fork of your reproduction](https://codesandbox.io/p/github/tombryden/experimental-apollo-suspense-bug/csb-t59sng/draft/charming-shape?file=%2Fsrc%2Fapollo%2Fapollo-wrapper.tsx%3A29%2C1-32%2C1) and everything works as expected. Hope this helps! 

Please reopen this issue or open a new issue if you need anything else!
