### ISSUE TITLE
is apollo client next compatible with unstable cache?

### ISSUE THREAD

**Issue by yanv1991** [apollographql/apollo-client-nextjs#250]
Just wondering if we can use apollo client next + [unstable cache](https://nextjs.org/docs/app/api-reference/functions/unstable_cache) in a RSC, if not, what alternatives could we consider to cache data in the server?

**Comment by phryneas** [comment]
That's a very broad question. What would you want to use it for?

Generally, Apollo Client will do normal `fetch` calls in the backend, so the `fetch` cache of Next.js would already apply - I'm not sure what you would use an additional cache layer for.

**Comment by niloodev** [comment]
You can't use on demand revalidation with this Apollo Client. So my idea was to use unstable_cache with apollo client (no cache) to cache the results (because I want to use query batching too)

But i ran into a problem, that is if a disable the cache of the fetch used in apollo, the entire route is gonna change to dynamic route (and I don't want)

**Comment by phryneas** [comment]
@niloodev I think you might be mixing up some things here: in RSC, we create a new instance of Apollo Client for every incoming request and these start with an empty cache, so all kind of caching beyond "while a request is happening" is the job of your framework's HTTP caching layer.

If you can use "on demand revalidation" without Apollo Client, I would assume that you can use it with Apollo Client as well.

If you're experiencing the opposite, could you share some code so we can see what you are trying to do here?

**Comment by niloodev** [comment]
@phryneas Basically I want to use Next on-demand-revalidation with query batching. I have an application that fetches many data from the same source (Wordpress) using GraphQL, the problem is: I can't predict how the query is gonna be, because I'm using query batching (and I have many different queries with different tags), so my idea was to use unstable_cache to make the cache layer above Apollo, that way I won't necessarily cache the requests, but the results.

I can't paste the code since it is from my job, but it would be awesome if you could help me with this.

(And yes, query batching in my application would be the perfect solution, but this kinda makes me HAVE to use Apollo Client since its the best GraphQL client with that functionality).

**Comment by niloodev** [comment]
@phryneas Okay I will do that, thank you for the help!
I was looking for some external advice since I never did that before.

**Comment by yanv1991** [comment]
hey @phryneas what is the correct way to handle fetchOptions per requests basis from a RSC? Maybe pass this as a parameter for every requests? The readme shows a `all or nothing` approach for this.

**Comment by phryneas** [comment]
@yanv1991 you'd do
```js
  const { data } = await query({
    query: QUERY,
    context: { fetchOptions: { cache: "no-store" } },
  });
```

**Comment by yanv1991** [comment]
closing this ticket since this was solved, thanks!
