### ISSUE TITLE
How to modify link uri if getClient can't receive arguments?

### ISSUE THREAD

**Issue by reilnuud** [apollographql/apollo-client-nextjs#273]

**Comment by phryneas** [comment]
Can you maybe provide a bit of code showcasing how you did it until now and where you were getting that from in the first place?

**Comment by phryneas** [comment]
It's probably better in an issue, since you'll not be the last person with this question :)

So I'll write a bit more of a "general answer here":

## Modifying a request URI as a "one-off" with an existing Apollo Client

Generally, there are a few different ways you can modify the `uri` of outgoing requests.

### From call site:

You can just use the `uri` value in `context` with an outgoing query

```ts
const { data } = await getClient().query(MY_QUERY, {
  context: {
    uri: "someOtherUri",
  },
  fetchPolicy: "no-cache",
});
```

### Using an uri callback

In an `uri` callback you have access to the full `operation`, which means that you could look at things like `operation.operationName` or `operation.variables` - or in this example, `operation.getContext()`.

```ts
export const { getClient } = registerApolloClient(() => {
  return new ApolloClient({
    cache: new InMemoryCache({
      // ...
    }),
    link: new HttpLink({
      uri(operation) {
        const context = operation.getContext();
        if (context.token) {
          return `${process.env.CMS_API_URL}?token=${context.token}`;
        }
        return process.env.CMS_API_URL;
      },
      // ...
    }),
  });
});
```

In your case, you'd then call that with `token` in the `context` - your call site wouldn't really be aware of the `uri` abstraction:

```ts
const { data } = await getClient().query(MY_QUERY, {
  context: {
    token: "myToken",
  },
  fetchPolicy: "no-cache",
});
```

### **❗Note that in both of these examples, I used `fetchPolicy: "no-cache"`.** 
That's not generally necessary, but something to consider: You are redirecting your Apollo Client to a different data source here. If you wouldn't use `no-cache`, the results from that other data source would get merged into your existing InMemoryCache - and in your case, where you probably have "original" and "draft" with the same typename and `id`, there's a risk that the drafts would overwrite the originals in the cache.

## Creating more than one cache

With that warning note from the last example - you might also want to consider creating more than one cache.

In that case, call `registerApolloClient` twice to create two independent cache instances per incoming request. 

```ts
const { getClient } = registerApolloClient(...)
// this will probably still need something like context to pass in the token for this cache on this request., unless you get the token from a cookie, then you can directly call `cookies()` inside the callback function in `registerApolloClient`.
const drafts = registerApolloClient(...)
```

later distinguish between `getClient()` calls and `drafts.getClient()` calls.

**Comment by phryneas** [comment]
Great! I'm gonna close this issue then. Have a great day!
