### ISSUE TITLE
Make ApolloNextAppProvider usable out of the box

### ISSUE THREAD

**Issue by Sam-Kruglov** [apollographql/apollo-client-nextjs#395]
I have to create a client component that forwards the children to it, I can't just use it directly. I think it should be usable in root layout as is without having to create an extra component
```tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body>
        <ApolloNextAppProvider makeClient={makeClient}>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
```
This gives an error  `⨯ Error: Unsupported Server Component type: undefined`

**Comment by phryneas** [comment]
We need you to create that additional file with "use client" on top so it is considered a client component by Next.js - you also could not pass `makeClient` over as a prop in a server component file, because the result of `makeClient` is non-serializable.

These are not constraints that we are adding, but constraints added by React and your Framework - there's no way around that.

**Comment by phryneas** [comment]
Because we cannot write `makeClient` for you (this is your configuration code), and it's impossible to pass `makeClient` from a server component into a client component. 
This has to happen in your code base.
