### ISSUE TITLE
Server components (server) vs useSuspenseQuery (client)

### ISSUE THREAD

**Issue by IvaanTorres** [apollographql/apollo-client-nextjs#55]
I am just setting up my project using these new apollo client features on NextJS 13. 
Everything works as expected. However, I have a big problem when I try to understand the need to use server components having already the useSuspenseQuery, which uses the ApolloNextProvider and handle data in an amazing way.

## Context:
I have 2 pages:
- Server component page:
    - I am importing the client to fetch data (getClient().query())
    - The server fetches the data and renders the updated info
    - The updated data is showing as expected in the page source since it's SSR
- Client component page (My doubts):
    - I use the useSuspenseQuery hook
    - At first, the request is made and then I get the data
    - After that render, the data is stored in cache so no more request for this
    - (¿?) The updated data is showing in the page source, something that is not happening when I use useQuery, why?

## Problems:
- Server component page:
    - At this time, I am seeing much people having troubles to revalidate the server components screens so we need to wait 30 seconds so it invalidates the cache automatically.
    - As a workaround, I am refreshing the nextjs 13 router on every link I click to go to this server side rendered page, so I am revalidating the screen in a hard way, something that makes the transition quite slow (not that reactive actually).

## Questions
- Why does the useSuspenseQuery fetch and show data much faster than useQuery at first render? (same situation, etc)
- Why does the useSuspenseQuery work as SSR rendering? It attaches the fetched data to the source page (Something incredible, knowing that it works instantly even if I refresh the page). I read the words "SSR Streaming". What is it actually?
- Knowing that useSuspenseQuery does everything what a server component should do (fetching data, for example), much faster in fact, why is it recommended to use server components to fetch data with apollo client? It works slower, harder to share cache with client side and creates a react tree much bigger and harder to manage than just using useSuspenseQuery on the client side...

**Comment by jerelmiller** [comment]
Hey @IvaanTorres 👋 

I'll do my best to answer your questions with the knowledge I have (@phryneas feel free to jump in if anything I say here is incorrect). I'll sort of answer your questions in a slightly different order.

> Why does the useSuspenseQuery work as SSR rendering?

This is the nature of Client Components within the React Server Components architecture with a Next.js 13 app that uses the `/app` directory. See the [Client Components](https://nextjs.org/docs/getting-started/react-essentials#client-components) docs that talk about how components are pre-rendered on the server and hydrated on the client. The hook just ties into this architecture.

> It attaches the fetched data to the source page (Something incredible, knowing that it works instantly even if I refresh the page). I read the words "SSR Streaming". What is it actually?

Because your client components first execute on the server in an SSR pass, you're not going to want to have to re-fetch again immediately on the client, otherwise you did all that work on the server for no reason. Instead, it would be much nicer if we were able to take the result of the fetch on the server, and just say "here you go" to the browser so that the data can be rendered immediately in the browser. This is what "SSR Streaming" is all about. Its a mechanism to take the data fetched on the server and make it available on the client. This is why you see the fetched data in the page source.

I'd highly recommend checking out [this React discussion](https://github.com/reactwg/react-18/discussions/37) that goes into super detail on the React 18 Suspense architecture in SSR. This helped make it click for me.

> Why does the useSuspenseQuery fetch and show data much faster than useQuery at first render? (same situation, etc)

Now that you know that Client Components execute in an SSR pass on the server, this comes down to how we fetch between the 2 hooks and the Suspense architecture in React 18 (again, see [this discussion](https://github.com/reactwg/react-18/discussions/37) for more details). Suspense is the key mechanism that allows you to stream updates to the browser as data becomes available.

Since `useQuery` is not a suspenseful hook, we can't take advantage of the streaming architecture in React 18 because we have no way to tell React "hey wait... I'm still fetching" without the use of Suspense. Because of this, we [disable fetches on the server](https://github.com/apollographql/apollo-client-nextjs/blob/4954601c71f130cd758b63ac7134e75844ca4534/package/src/ssr/hooks.ts#L20) for the `useQuery` hook by making that query a `cache-only` query (this does however mean that if all of that data is in the cache, you will have that data preloaded).

Since we don't fetch on the server with `useQuery`, this means we can't actually execute that query until its rendered in the browser. The simple answer here is: we are able to execute the query on the server with `useSuspenseQuery` but have to wait for the browser for `useQuery`, so `useSuspenseQuery` is going to get you results faster.

> why is it recommended to use server components to fetch data with apollo client? It works slower, harder to share cache with client side and creates a react tree much bigger and harder to manage than just using useSuspenseQuery on the client side...

I'd say its a stretch to say we "recommend server components to fetch" because these are patterns that we are still all figuring out. We enable you to fetch in server components, but I'd say these are patterns that we as a community are still figuring out. Some apps may find heavier use of server components because its data rarely changes. Other apps may find that server components are seldom used because the app is highly dynamic. I don't think we yet have a black-and-white recommendation on when to use one vs the other. The ways in which we are used to building React apps thus far are changing and its going to require a renewed way of thinking. We are by no means experts on this quite yet 😅.

You're exactly right about the cache though. I'd go so far as to say, its not just harder to share the cache, but currently impossible. Server components don't share their cache with Client Components, so there is actually no way to sync the cache between the two. This is why we give the disclaimer we do in our README:

> ❗️ We do handle "RSC" and "SSR" use cases as completely separate.

From what I've seen, server components are going to be really good for things such as layout, or components that render data that rarely (or never) changes during the lifecycle of your app (think `currentUser` and its fields). Highly dynamic components aren't because changes here would require a full page invalidation (at least as far as I understand).

This is going to be very app-dependent. Some are much more dynamic than others. You may find yourself writing client components much more often than server components, or vice versa. If you find some good patterns here yourself, we'd love to hear them!

Hope this helps!

**Comment by IvaanTorres** [comment]
Hey @jerelmiller ! :wave: Thanks for your fast response. Your help made me realise about many things that happen in React, I really appreciate that :)

## Introduction (React 17 to React 18) [New features React 18](https://github.com/reactwg/react-18/discussions/5)
- NextJS 13 uses that hydrateRoot() (createRoot() with hydration support) as its root by default and the new API renderToPipeableStream() on server-side to make possible the SSR Streaming. If I'm right, that's why useSuspenseQuery works as it does unlike useQuery, isn't it? The only difference between them is the use of Suspense.

## Summary
If I understood well (don't hesitate to correct me if necessary): 

- Not using SSR with legacy version of React (Waterfall. One step must finish before the next one starts): 
    - Step 1: Pre-render the non-interactive html on the server (no additional js like fetches, etc). Then, when the SSR tree is fully created, send it to the client.
    - Step 2: Load ALL the client-side js for ALL components of this page before hydrating. (Client React tree structure must match the pre-rendered SSR tree to assign event handlers). Those are the *.js files loaded on the network tab panel from the dev tools, right?
    - Step 3: React hydrates ALL the non-interactive server-rendered page (plain text html) with the js on the client (which is already loaded) while the component is rendering and so, making it interactive (Event handlers, etc).
    - Step 4: Fetch the data once the component is initialized/mounted and rendered (Loading states appear).
   
- Using SSR with legacy version of React (Waterfall. One step must finish before the next one starts): 
    - Step 1: Load server-side js (Fetch ALL data, etc)
    - Step 2: Pre-render the server-side non-interactive html (with the js server-side processed data in plain text, like the fetch promises) when ALL promises/collected data are resolved (Some pieces of complex logic or slow API's may make this slow). Then, when the SSR tree is fully created, send it to the client.
    - Step 3: Load ALL the client-side js for ALL components before hydrating (Client React tree structure must match the pre-rendered SSR tree to assign event handlers). Those are the *.js files loaded on the network tab panel from the dev tools, right?
    - Step 4: React hydrates ALL the non-interactive server-rendered page (plain text html) with the js on the client (which is already loaded) while rendering the component and so, making it interactive (event handlers, etc). However, we can't interact until ALL the content is hydrated so slow pieces of logic (big client js files) may create a waterfall performance problem.
  
- SOLUTION (React 18 and NextJS 13) - Using Client components with Suspense when we do really have dynamic data (Use SSR Streaming) and server components when the data barely changes during the time (as you said, it can change depending the app context): 
    - Step 1 - SSR Streaming before the data is fetched: Using Suspense, we can stream html as we are resolving it (Don't need to wait heavy requests to stream all the html at once). The pieces of html that are resolved after the stream of html, are also streamed with a light-weight js bundle to place it correctly in the DOM.   
    - Step 2 - Hydrating the page before all the code has loaded: Thanks to the Suspense, we can start hydrating the client without having to wait the js from a possibly heavy-weight code (Low internet, complex logic, etc).
    - Step 3 - Hydrating the page before all the HTML has been streamed: React can start hydrating the rest of components even if we didn't received the complex html part from the server (heavy request, for example).
    - Step 4: Interacting with the page before all the components have hydrated: Even if a suspended component is still rehydrating, we can use event handler on the rest, which are already available and interactive.

## Questions
However, after reading serveral times your answers and the threads that you shared with me, I don't get some things:

- If I use a client component without suspense, it acts like the first section of the summary?
- If I use a client component with suspense, it acts like the solution from the summary?
- If I use a server component with or without suspense, it always act like the second section of the summary?

- SSR = Server components? If I understood well, SSR is used in both client and server component when pre-rendering thanks to the new version "React 18" (I used useSuspenseQuery in a client component and you told me that I was using SSR streaming. Then, I don't get how can be possible to see the fetched data in the source page if I'm using a client component and not a server component even if it's using SSR rendering as well. Client components using the suspense in React 18 can fetch data on the server-side and attach it to the streamed HTML directly ? I thought client components just send the empty HTML rendered from the server and then, once the client is hydrated, it fetches the data ).

- If client components using suspense can fetch data on server-side and append it to the streamed html before sending it to the client, what is the difference between this and server components?

- Knowing the several advantages of React 18 and the fact that you said that the useQuery hook can just act as 'only-cache' in a suspense case, why not just replacing useQuery() for the new useSuspenseQuery() ? It works much better for UX and take advantage of those new features of React 18 thanks to its Suspense. Moreover, we can also get the data directly from the cache.

## Thanks
Thank you in advance for taking the time to explain me this. I'm new with this new apollo hook and I realized that I wasn't taking advantage of the suspense features of the new version of React. :wave:
