### ISSUE TITLE
Error when trying to get a client in middleware

### ISSUE THREAD

**Issue by tremby** [apollographql/apollo-client-nextjs#66]
I have a piece of [middleware](https://nextjs.org/docs/app/building-your-application/routing/middleware) which handles redirections. It needs to fetch the list of redirection patterns from the CMS and I've been doing this via Apollo.

I'm trying to move to this package and I'm not sure if I'm meant to be using `getClient` from my ApolloClient file or something else. When I use `getClient`, I get an error: "`registerApolloClient` should only be used in a React Server Component context - in Client Componencts, use the `ApolloNextAppProvider`!". It disappears as soon as I delete my middleware.ts file. This isn't a client component, though, is it?

**Comment by tremby** [comment]
I tried sidestepping the check to see if it'd just work, and I get a new error that React.cache doesn't exist. That sent me down the rabbit hole of figuring out why -- it appears that React.cache is an unreleased React feature only available on future React versions, and that Next bundles such a future version (without it being mentioned in `npm ls react`). I guess it's only used in some areas of a Next project. In middleware files, the version of React installed by the developer is used instead.

So I installed the canary version, sidestepped the check, and now it complains that it can't find `react-server-dom-webpack/client.edge`, and that's as far down the rabbit hole as I want to go.

Is it really right for this package to have a dependency of react ^18.2.0 and yet go ahead and attempt to use React.cache, which doesn't exist until 18.3 or later?

Is React.cache replaceable?

Maybe I'm misguided and I shouldn't be doing a data fetch as part of a middleware? I'm not really sure how to avoid it -- I need this data to know what to redirect to where, and then it's fine to be cached pretty long term.

So I tried just not using Apollo here, and using `fetch` directly. This works OK, but now I find that this is not Next's patched `fetch`, and so the result isn't cached. This is exactly what I don't want...

**Comment by tremby** [comment]
The best I could come up with, with some help from folks in the Next.js discord, was to make an API route which does the fetch and the work, and to call this API route from the middleware via (uncached) fetch. I don't love it; it's adding about 50ms to each request. And an app calling itself via HTTP seems icky.

**Comment by phryneas** [comment]
Middleware exist in their own world, completely outside of React Server or Client components. 
To be honest, you'll probably do best by just calling `new ApolloClient()` within that middleware - as it lives in a completely different environment, you won't be able to share anything between it and React components anyways - and you likely also shouldn't share that ApolloClient instance between multiple middleware, since that would mix up data between different users.

As for dependencies: We don't have a dependency on React 18.3. We have a `peerDependency` on React in "something with version 18", as that is the closest we can get to anything. In the end, the version of React is dictated by Next.js, since they ship their own version of React that is not published anywhere on `npm`.  
On the upside, that version of React is 100% guaranteed to have `React.cache`, which has been confirmed to us both by Next.js team members and React team members.

**Comment by tremby** [comment]
Alright. Maybe it's worth detecting middleware and adding an error message basically saying "don't use this in a middleware"? Though anyone coming up with the error I saw will likely find their way here, so maybe that's good enough.

> We don't have a dependency on React 18.3. We have a peerDependency on React in "something with version 18"

Ah yes it's your dev dependency which asks for 18.2 or higher.

Thanks again for your help.
