### ISSUE TITLE
Question about a statement in RFC rather than an issue.

### ISSUE THREAD

**Issue by iamrahulrnair** [apollographql/apollo-client-nextjs#84]
> We want to make sure that the Apollo Client does not have to be recreated for every query, but we also don't necessarily want to share it between different requests, as the client could be accessing cookies in a dynamic render, so potentially sensitive data could be shared between multiple users on accident.

Apollo client does not have to be recreated for every query because it is expensive to do so?, and why exactly we don't want to share it between different requests? is it because each request is different and there is no way to distinguish each request from a client in server?

> as the client could be accessing cookies in a dynamic render, so potentially sensitive data could be shared between multiple users on accident.

How sensitive data shared with multiple users if the apollo client is shared between different request?

**Comment by plausible-phry** [comment]
The server does not know who makes a request, it just gets a request from someone.

So we have to treat every incoming request as an individual user - we don't know if it's someone new or someone coming back.

If you had one cache for all those requests, and user A would do a "myFriendsQuery" and then user B were to do the "myFriendsQuery", user B would get the friends of user A.

That's why we have to create a new individual `ApolloClient` for each incoming request - request meaning "someone loads the page and we render the page from start to finish".


That said, we don't want to create a new Apollo Client for every query. Imagine that three components used that "myFriendsQuery" - if they are rendered for the same incoming request, we only want to send that query to the GraphQL server only once and read it from the cache twice. If we created a new client for every query, that would mean that we would have to send the "myFriendsQuery" to the GraphQL sever three times.

**Comment by iamrahulrnair** [comment]
> The server does not know who makes a request, it just gets a request from someone.
> 
> So we have to treat every incoming request as an individual user - we don't know if it's someone new or someone coming back.
> 
> If you had one cache for all those requests, and user A would do a "myFriendsQuery" and then user B were to do the "myFriendsQuery", user B would get the friends of user A.
> 
> That's why we have to create a new individual `ApolloClient` for each incoming request - request meaning "someone loads the page and we render the page from start to finish".
> 
> That said, we don't want to create a new Apollo Client for every query. Imagine that three components used that "myFriendsQuery" - if they are rendered for the same incoming request, we only want to send that query to the GraphQL server only once and read it from the cache twice. If we created a new client for every query, that would mean that we would have to send the "myFriendsQuery" to the GraphQL sever three times.

Sure got the idea. Another confusing part around cache is, [here](https://www.apollographql.com/blog/apollo-client/next-js/next-js-getting-started/#using-apollo-client-for-server-side-rendered-page-data) the author uses apollo client to request data in server side, does this means there is no cacheing in server? this uses page router.

**Comment by plausible-phry** [comment]
Doing it in the `pages` directory with `getServerSideProps` uses much the same principle - a new client for every request. There is no caching going on on the server (unless you call the same `client.query` multiple times), but you can use this approach to fill the cache on the server and merge it into the browser's Apollo Client - although the blog article you linked doesn't seem to show that aspect.

**Comment by iamrahulrnair** [comment]
Thanks @plausible-phry got it.
