### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Bowriverstudio** [apollographql/apollo-client-nextjs#94]
I'm not sure if this is related to my specific setup or is related to the apollo-client-nextjs

In my next-js setup everything works as expected.

I use storybook and am getting this error

registerApolloClient` should only be used in a React Server Component context - in Client Components, use the `ApolloNextAppProvider`!

```js
function makeStorybookClient() {
    const fetchOptions = process.env.NEXT_PUBLIC_VERCEL_ENV !== "production"
        ? { cache: "no-store" }
        : {};

    const httpLink = new HttpLink({
        // this needs to be an absolute url, as relative urls cannot be used in SSR
        uri: `${process.env.NEXT_PUBLIC_WORDPRESS_URL}/graphql`,
        // you can disable result caching here if you want to
        // (this does not work if you are rendering your page with `export const dynamic = "force-static"`)
        fetchOptions,
    });

    return new NextSSRApolloClient({
        // cache: new NextSSRInMemoryCache(),
        link:
            httpLink,
    });
}



export function StorybookApolloWrapper({ children }) {
    return (
        <ApolloNextAppProvider
            makeClient={makeStorybookClient}
        >
            {children}
        </ApolloNextAppProvider>
    );
}


export const MyStory = () => (
  <StorybookApolloWrapper>
    <MyComponent />
  </StorybookApolloWrapper>
);

```

Any thoughts on this?

Thanks.

**Comment by jerelmiller** [comment]
Hey @Bowriverstudio 👋 

Would you mind upgrading to the latest version ([v0.4.2](https://github.com/apollographql/apollo-client-nextjs/releases/tag/v.0.4.2) at the time of this writing). That version contains #90 which changed how the environment is detected (in fact you can see that specific error message [removed here](https://github.com/apollographql/apollo-client-nextjs/pull/90/files#diff-7e967bbcbac56c6150444502ee78f19bd5e48942b8e19f5fe09e7fd073425a6cL9)). See if this version works for you!

**Comment by Bowriverstudio** [comment]
@jerelmiller - Thank you for the suggestion.   I just updated to 0.4.2 and am getting a new error

This module cannot be imported from a Client Component module. It should only be used from a Server Component.
Error: This module cannot be imported from a Client Component module. It should only be used from a Server Component.

I am using a client component

'use client'
import { useSuspenseQuery } from "@apollo/experimental-nextjs-app-support/ssr";

The component works as I expect in nextjs but not in storybook.  

Thank you

**Comment by phryneas** [comment]
This is likely caused by that component's file importing *something* from a file (that maybe imports another file and so on) with one of those files importing `@apollo/experimental-nextjs-app-support/rsc`.
This warning can only come from the `import "server-only";` statement in https://github.com/apollographql/apollo-client-nextjs/blob/b7db32f5e7ca37425b00353e6bdb890d756617f5/package/src/rsc/registerApolloClient.tsx - and if you don't import that file in any way, the error message cannot come up.

Are you using barrel export files (`index.js` reexporting everything in a folder) by chance?

**Comment by mvandergrift** [comment]
I was having a similar error pop up while migrating code that used nested barrel exports.  Server modules were inadvertently being referenced down the tree and I didn't think about it since they weren't being destructured during the import. This was triggering the React error. Easy enough to solve by directly referencing the modules I needed, but I can imagine it will require  some restructuring of project exports to avoid this.

**Comment by Bowriverstudio** [comment]
Thank you @phryneas  and @mvandergrift  - the barrel export files was the issue.  It is now working.
